---
title: "Running the simulation"
date: "`r date()`"
---

```{r doc_setup, include=FALSE}
fig.dim <- 5
knitr::opts_chunk$set(fig.height=fig.dim,fig.width=2*fig.dim,fig.align='center')
```

Setting up the simulation
-------------------------

First we need to decide where the loci under selection are.
Here `qtl` is a named list, one element per chromosome,
and each element of the list is a data frame
whose columns give the name of the locus,
the selection coefficient,
and the position in Morgans.

```{r setup_qtl}
qtl=list(
         chr1=data.frame(
                    traits = c("underdominant"),
                    s = c(0.1),
                    pos = c(0.5)
                )
    )
```

Now, let's set up the population,
which means specifying the number of individuals,
the number of demes,
the width of the zone in real units,
and the dispersal SD ($\sigma$).
Our locus has a selection coefficient of `r qtl[[1]]$s`,
so the cline width will be about `r round(1/sqrt(qtl[[1]]$s),digits=1)`$\sigma$ wide;
so we'll take our zone to be four times that,
and measure distance in units of $\sigma$:
```{r setup_pop}
zone.width <- ceiling(4/sqrt(qtl[[1]]$s))  # in real units
nind <- 1000
ndeme <- 50
sigma <- 1 # in real units
deme.spacing <- zone.width/ndeme
sigma.demes <- sigma/deme.spacing # in units of demes
```
The discretized dispersal kernel moves as $\lfloor Z+1/2 \rfloor$,
where $Z \sim N(0,\sigma_\text{demes}^2)$;
let's check this has SD close to $\sigma$:
```{r check_sigma}
zz <- floor( rnorm( 1e6, mean=1/2, sd=sigma.demes ) )*deme.spacing
sd(zz)
```
That's pretty good.



Running a simulation
--------------------

To run the simulation,

